from utils.database import db, Product

STORE_PRODUCTS = [
    {"name": "Syngenta Brinjal F1 Hybrid Seeds", "brand": "Syngenta", "category": "seed", "sub_category": "vegetable_seed", "price": 285, "original_price": 320, "stock": 200, "unit": "10 g pack", "description": "High-yielding F1 hybrid brinjal variety. Large, glossy, dark-purple fruits. Excellent shelf life and disease resistance.", "usage_instructions": "Sow in nursery bed at 0.5 cm depth. Transplant after 30-35 days. Spacing: 60x60 cm.", "safety_info": "Non-toxic. Store in a cool, dry place.", "active_ingredient": "Hybrid F1 Genetic Material", "crop_suitable_for": "Brinjal / Eggplant", "image_url": "https://m.media-amazon.com/images/I/61rU8m2mQOL._SX679_.jpg", "rating": 4.5, "reviews_count": 234, "is_featured": True},
    {"name": "Mahyco Tomato MHTJ-3 Hybrid Seeds", "brand": "Mahyco", "category": "seed", "sub_category": "vegetable_seed", "price": 349, "original_price": 400, "stock": 180, "unit": "10 g pack", "description": "MHTJ-3 determinate tomato hybrid with TLCV tolerance. Round firm red fruits 80-90 g.", "usage_instructions": "Sow in nursery. Transplant at 4-5 leaf stage. Spacing 60x45 cm.", "safety_info": "Non-toxic. Store below 20 C.", "active_ingredient": "Hybrid F1 Genetics", "crop_suitable_for": "Tomato", "image_url": "https://m.media-amazon.com/images/I/71z06B7sM9L._SX679_.jpg", "rating": 4.7, "reviews_count": 512, "is_featured": True},
    {"name": "East-West Chilli Lal Bahar Hybrid", "brand": "East-West Seeds", "category": "seed", "sub_category": "vegetable_seed", "price": 199, "original_price": 240, "stock": 300, "unit": "10 g pack", "description": "Lal Bahar chilli hybrid. Bright red pungent fruits. CLCV tolerant.", "usage_instructions": "Nursery sowing. Transplant after 35 days. Spacing 45x30 cm.", "safety_info": "Non-toxic. Store in sealed pouch.", "active_ingredient": "Hybrid F1 Genetics", "crop_suitable_for": "Chilli / Hot Pepper", "image_url": "https://m.media-amazon.com/images/I/81fH+0y4t-L._SX679_.jpg", "rating": 4.3, "reviews_count": 189, "is_featured": False},
    {"name": "Seminis Okra Hybrid Seeds", "brand": "Seminis", "category": "seed", "sub_category": "vegetable_seed", "price": 175, "original_price": 210, "stock": 220, "unit": "250 g pack", "description": "High-performing okra hybrid. Dark green fruits. YVMV tolerant. First harvest in 45 days.", "usage_instructions": "Direct sowing. Spacing 45x30 cm. Harvest every 2-3 days.", "safety_info": "Imidacloprid seed treatment - keep from children.", "active_ingredient": "Hybrid F1 + Imidacloprid", "crop_suitable_for": "Okra / Bhindi", "image_url": "https://m.media-amazon.com/images/I/61t-zJ+-zEL._SX679_.jpg", "rating": 4.4, "reviews_count": 321, "is_featured": True},
    {"name": "Pioneer 30V92 Maize Hybrid Seeds", "brand": "Pioneer Corteva", "category": "seed", "sub_category": "grain_seed", "price": 1250, "original_price": 1400, "stock": 80, "unit": "4 kg bag", "description": "High-yielding kharif maize hybrid. 100-105 day maturity. Excellent stalk strength. Resistant to Turcicum Leaf Blight.", "usage_instructions": "Sow at 60x20 cm. Seed rate 20-25 kg/ha. Apply NPK 150-75-60 kg/ha.", "safety_info": "Treated with Thiram and Metalaxyl. Avoid consuming.", "active_ingredient": "Hybrid F1 + Thiram + Metalaxyl", "crop_suitable_for": "Maize / Corn", "image_url": "https://m.media-amazon.com/images/I/71R2D+i0i+L._SX679_.jpg", "rating": 4.6, "reviews_count": 445, "is_featured": True},
    {"name": "Kaveri KB-44 Cotton Bt Hybrid Seeds", "brand": "Kaveri Seeds", "category": "seed", "sub_category": "grain_seed", "price": 780, "original_price": 850, "stock": 120, "unit": "450 g pack", "description": "KB-44 Bt cotton hybrid with bollworm protection. High ginning outturn. Suitable for rainfed and irrigated conditions.", "usage_instructions": "Sow 1.5m x 60cm. Maintain 5 percent refuge with non-Bt cotton.", "safety_info": "Bt variety - do not use as food.", "active_ingredient": "Bt Gene Cry1Ac and Cry2Ab", "crop_suitable_for": "Cotton", "image_url": "https://m.media-amazon.com/images/I/81Z-yq40yBL._SX679_.jpg", "rating": 4.3, "reviews_count": 267, "is_featured": False},
    {"name": "Nuziveedu NS 7325 Soyabean Seeds", "brand": "Nuziveedu Seeds", "category": "seed", "sub_category": "grain_seed", "price": 450, "original_price": 500, "stock": 160, "unit": "5 kg bag", "description": "NS 7325 soyabean variety. 95-100 day maturity. High protein 42 percent. Tolerant to Yellow Mosaic.", "usage_instructions": "Sow 45x5 cm. Seed rate 70-75 kg/ha. Inoculate with Rhizobium.", "safety_info": "Non-toxic. Store in cool dry place.", "active_ingredient": "Open-pollinated improved variety", "crop_suitable_for": "Soyabean", "image_url": "https://m.media-amazon.com/images/I/81R6v9K9-1L._SX679_.jpg", "rating": 4.1, "reviews_count": 134, "is_featured": False},
    {"name": "Roundup 41% SL Glyphosate", "brand": "Bayer CropScience", "category": "pesticide", "sub_category": "herbicide", "price": 1150, "original_price": 1300, "stock": 75, "unit": "1 litre bottle", "description": "Broad-spectrum non-selective systemic herbicide. Controls annual and perennial weeds and grasses. Pre-sowing use only.", "usage_instructions": "Mix 1.3-2.6 litre/acre in 200 litres water. Spray when weeds 10-15 cm tall.", "safety_info": "DANGER: Avoid contact with eyes and skin. Wear gloves and goggles.", "active_ingredient": "Glyphosate 41% SL", "crop_suitable_for": "Pre-sowing all field crops, orchards", "image_url": "https://m.media-amazon.com/images/I/51gWpPq019L._SX679_.jpg", "rating": 4.4, "reviews_count": 678, "is_featured": True},
    {"name": "Nominee Gold Bispyribac-sodium", "brand": "Bayer CropScience", "category": "pesticide", "sub_category": "herbicide", "price": 680, "original_price": 750, "stock": 90, "unit": "100 ml bottle", "description": "Post-emergence herbicide for paddy. Controls Barnyard Grass, Sedges, Broadleaf weeds without affecting crop.", "usage_instructions": "Apply 100-150 ml/acre. Apply 15-20 days after transplanting.", "safety_info": "CAUTION: Slightly toxic. PHI: 60 days.", "active_ingredient": "Bispyribac-sodium 10% OD", "crop_suitable_for": "Paddy / Rice", "image_url": "https://m.media-amazon.com/images/I/71lU4o8z3yL._SX679_.jpg", "rating": 4.6, "reviews_count": 392, "is_featured": True},
    {"name": "Dithane M-45 Mancozeb 75% WP", "brand": "Dow AgroSciences", "category": "pesticide", "sub_category": "fungicide", "price": 320, "original_price": 380, "stock": 110, "unit": "500 g pack", "description": "Broad-spectrum contact fungicide. Controls Early Blight, Late Blight, Downy Mildew, Leaf Spot.", "usage_instructions": "Mix 400-600 g in 200 litres water per acre. Repeat every 10-14 days.", "safety_info": "WARNING: Irritant. Wear gloves and mask. PHI: 3 days for vegetables.", "active_ingredient": "Mancozeb 75% WP", "crop_suitable_for": "Tomato, Potato, Grapes, Chilli, Onion, Rice, Wheat, Cotton", "image_url": "https://m.media-amazon.com/images/I/61F1Q1gR5WL._SX679_.jpg", "rating": 4.5, "reviews_count": 891, "is_featured": True},
    {"name": "Ridomil Gold Metalaxyl-M + Mancozeb", "brand": "Syngenta", "category": "pesticide", "sub_category": "fungicide", "price": 845, "original_price": 950, "stock": 65, "unit": "500 g pack", "description": "Premium combination fungicide. Best for Downy Mildew and Late Blight with curative and protective action.", "usage_instructions": "Use 400 g per acre in 200 litres water. Max 3 sprays.", "safety_info": "WARNING: Harmful if swallowed. Wear PPE. PHI 14 days.", "active_ingredient": "Metalaxyl-M 4% + Mancozeb 64% WP", "crop_suitable_for": "Potato, Tomato, Grapes, Onion, Cucumber", "image_url": "https://m.media-amazon.com/images/I/61n43n4AHTL._SX679_.jpg", "rating": 4.7, "reviews_count": 543, "is_featured": False},
    {"name": "Bavistin 50% WP Carbendazim", "brand": "BASF India", "category": "pesticide", "sub_category": "fungicide", "price": 260, "original_price": 300, "stock": 130, "unit": "250 g pack", "description": "Systemic broad-spectrum fungicide. Controls Powdery Mildew, Collar Rot, Damping Off, and Smut.", "usage_instructions": "Foliar: 0.05-0.1% solution. Seed treatment: 2g/kg seed.", "safety_info": "CAUTION: Wear gloves and mask. PHI: 15 days.", "active_ingredient": "Carbendazim 50% WP", "crop_suitable_for": "Wheat, Rice, Sugarcane, Banana, Mango, Cotton, Vegetables", "image_url": "https://m.media-amazon.com/images/I/51h1T2j3e1L._SX679_.jpg", "rating": 4.3, "reviews_count": 712, "is_featured": False},
    {"name": "Confidor 200 SL Imidacloprid", "brand": "Bayer CropScience", "category": "pesticide", "sub_category": "insecticide", "price": 550, "original_price": 630, "stock": 95, "unit": "100 ml bottle", "description": "Systemic neonicotinoid insecticide. Effective against Aphids, Whiteflies, Jassids, Thrips, Mealybugs.", "usage_instructions": "Mix 0.3-0.5 ml/litre water. Drench soil or foliar spray.", "safety_info": "WARNING: Highly toxic to bees. Do not apply during flowering. PHI: 7 days.", "active_ingredient": "Imidacloprid 200 SL", "crop_suitable_for": "Cotton, Tomato, Chilli, Paddy, Brinjal, Groundnut", "image_url": "https://m.media-amazon.com/images/I/51H5V1H9n5L._SX679_.jpg", "rating": 4.5, "reviews_count": 934, "is_featured": True},
    {"name": "Coragen 20% SC Chlorantraniliprole", "brand": "FMC Corporation", "category": "pesticide", "sub_category": "insecticide", "price": 1980, "original_price": 2200, "stock": 45, "unit": "60 ml bottle", "description": "Diamide insecticide for caterpillar pests. Controls Stem Borer, Leaf Folder, Fruit Borer. Long residual activity.", "usage_instructions": "Mix 40-60 ml/acre in 200 litres water. Provides 2-3 week protection.", "safety_info": "CAUTION: Wear gloves and mask. PHI: 3 days for vegetables.", "active_ingredient": "Chlorantraniliprole 20% SC", "crop_suitable_for": "Rice, Sugarcane, Tomato, Cabbage, Cotton, Brinjal, Pulses", "image_url": "https://m.media-amazon.com/images/I/61o3rY3q1JL._SX679_.jpg", "rating": 4.8, "reviews_count": 621, "is_featured": True},
    {"name": "Multiplex Neem NSKE 5%", "brand": "Multiplex Bio-Tech", "category": "medicine", "sub_category": "bio_pesticide", "price": 180, "original_price": 220, "stock": 200, "unit": "500 ml bottle", "description": "Botanical bio-pesticide from Neem Seed Kernel. Controls Aphids, Thrips, Leafhoppers. Safe for beneficial insects.", "usage_instructions": "Mix 50 ml/litre. Spray every 7-10 days in morning or evening.", "safety_info": "Non-toxic. No PHI restrictions. Safe for organic farming.", "active_ingredient": "Azadirachtin Neem Seed Kernel Extract", "crop_suitable_for": "All vegetables, fruits, flowers, pulses", "image_url": "https://m.media-amazon.com/images/I/61vYpS-8B-L._SX679_.jpg", "rating": 4.3, "reviews_count": 445, "is_featured": False},
    {"name": "Amistar Top Azoxystrobin Difenoconazole", "brand": "Syngenta", "category": "medicine", "sub_category": "systemic_fungicide", "price": 920, "original_price": 1050, "stock": 55, "unit": "200 ml bottle", "description": "Premium combination fungicide with systemic activity for protection, cure, and eradication of fungal diseases.", "usage_instructions": "Mix 1 ml/litre water. Spray at disease onset. Max 2 applications.", "safety_info": "WARNING: Use PPE. PHI 7-14 days.", "active_ingredient": "Azoxystrobin 18.2% + Difenoconazole 11.4% SC", "crop_suitable_for": "Wheat, Rice, Maize, Vegetables, Fruits, Soyabean", "image_url": "https://m.media-amazon.com/images/I/61T+1hV9rOL._SX679_.jpg", "rating": 4.6, "reviews_count": 387, "is_featured": True},
    {"name": "Pseudomonas fluorescens Bio-Pesticide", "brand": "T-Stanes", "category": "medicine", "sub_category": "bio_control", "price": 150, "original_price": 180, "stock": 250, "unit": "1 litre bottle", "description": "Biological fungicide and plant growth promoter. Controls Fusarium, Pythium, Rhizoctonia. Promotes root growth.", "usage_instructions": "Seed treatment: 10 ml/kg seed. Soil drench: 1 litre in 200 litres water per acre.", "safety_info": "Completely safe. Do not mix with chemical pesticides.", "active_ingredient": "Pseudomonas fluorescens 10^8 CFU per ml", "crop_suitable_for": "All crops - especially rice, tomato, potato, groundnut", "image_url": "https://m.media-amazon.com/images/I/61C2C9l7s3L._SX679_.jpg", "rating": 4.2, "reviews_count": 212, "is_featured": False},
    {"name": "Copper Oxychloride 50% WP", "brand": "Indofil Industries", "category": "medicine", "sub_category": "bactericide_fungicide", "price": 195, "original_price": 240, "stock": 160, "unit": "500 g pack", "description": "Multi-purpose bactericide and fungicide. Controls Bacterial Blight, Citrus Canker, and fungal diseases.", "usage_instructions": "Mix 2.5-3 g per litre water. Spray 2-3 times at 10-14 day intervals.", "safety_info": "WARNING: Toxic to fish. Wear gloves and goggles. PHI: 5 days.", "active_ingredient": "Copper Oxychloride 50% WP", "crop_suitable_for": "Tomato, Potato, Citrus, Mango, Grapes, Coffee, Paddy", "image_url": "https://m.media-amazon.com/images/I/71T1T1Y7r+L._SX679_.jpg", "rating": 4.1, "reviews_count": 267, "is_featured": False},
    {"name": "IFFCO NPK 19-19-19 Water Soluble", "brand": "IFFCO", "category": "fertilizer", "sub_category": "water_soluble_fertilizer", "price": 880, "original_price": 980, "stock": 200, "unit": "5 kg bag", "description": "Balanced NPK 19:19:19 water-soluble fertilizer for fertigation and foliar spray. Equal N, P, K for balanced nutrition.", "usage_instructions": "Fertigation: 5-10 kg/acre. Foliar: 5-10 g/litre. Apply at vegetative and reproductive stages.", "safety_info": "Non-toxic. Wear gloves in bulk handling. Store in dry place.", "active_ingredient": "N-P-K 19-19-19 water soluble", "crop_suitable_for": "All crops - vegetables, fruits, and cash crops", "image_url": "https://m.media-amazon.com/images/I/71S9bV9Tq9L._SX679_.jpg", "rating": 4.5, "reviews_count": 678, "is_featured": True},
]


def seed_store_data():
    if Product.query.count() == 0:
        for p_data in STORE_PRODUCTS:
            product = Product(**p_data)
            db.session.add(product)
        db.session.commit()
        print(f"Seeded {len(STORE_PRODUCTS)} products.")
    else:
        print("Products already exist. Skipping seed.")

